// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// MIGRAÇÃO (Fatia 5): o app não usa mais o Supabase — todas as telas/hooks foram
// migrados para o backend Python (`@/integrations/api`). Este client é vestigial e
// será removido no cutover. NÃO derrube o app no boot quando as envs do Supabase
// não existirem (era a causa do "supabaseUrl is required" → tela branca): só cria o
// client quando configurado; caso contrário exporta `null`.
export const supabase =
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : (null as unknown as ReturnType<typeof createClient<Database>>);
